### ISSUE TITLE
自定义进程的时候，我在本地调试，如果电脑休眠，再次打开电脑，进程就不执行了，一直可以写入任务，但是不消费

### ISSUE THREAD

**Issue by prettythings** [1107012776/easy-swoole-rabbitmq#10]
go(function () {
            $MqQueue = MqQueue::getInstance()->refreshConnect();
            $MqQueue->consumer()->setMoniterWaitError(function (\Exception $e){
                //   \EasySwoole\EasySwoole\Logger::getInstance()->log('moniterWaitErro' . var_export($e, true),\EasySwoole\Log\LoggerInterface::LOG_LEVEL_INFO,'debug');

            })->setConfig('kd_sms_send_ex','hello')->listen(function(MqJob $obj) {
                var_dump($obj->getJobData(),'receive');
                \EasySwoole\EasySwoole\Logger::getInstance()->log('receive' . var_export($obj, true),\EasySwoole\Log\LoggerInterface::LOG_LEVEL_INFO,'debug');
                return true;   //使用return true终止执行下面的代码
                //$otherMq = MqQueue::getInstance()->refreshConnect();
               // $newJob = new MqJob();
               // $newJob->setJobData('otherMq queue'.date('Y-m-d H:i:s', time()));
                //$res = $otherMq->producer()->setConfig('kd_sms_send_ex','hello_otherMq')->push($newJob);
               // var_dump($res,'send otherMq queue');
              //  \EasySwoole\EasySwoole\Logger::getInstance()->log('send otherMq queue' . var_export($newJob, true),\EasySwoole\Log\LoggerInterface::LOG_LEVEL_INFO,'debug');
               // $otherMq->closeConnection();
            });
        });

**Comment by 1107012776** [comment]
正常，那边的捕获moniter会有这个错误的
