### ISSUE TITLE
如果异常不处理，建议抛出给应用层处理，比如断线重连

### ISSUE THREAD

**Issue by hkj1994** [1107012776/easy-swoole-rabbitmq#3]
![image](https://user-images.githubusercontent.com/41996511/123242148-5231f500-d514-11eb-9765-377e2516f1e7.png)

**Comment by 1107012776** [comment]
好的

**Comment by 1107012776** [comment]
已修复v3.2   
```
        while (count($channel->callbacks)) {
            $channel->wait(null, false, 10);  //等待出现异常需要自行捕获，这边不做处理
        }

```

**Comment by 1107012776** [comment]
v3.6   已经添加了一个回调函数处理那个异常

**Comment by 1107012776** [comment]
while (count($channel->callbacks)) {
            try {
                $channel->wait(null, false, $waitTime);
            } catch (\Exception $e) {
                !empty($moniterWaitErrorCallable) && $moniterWaitErrorCallable($e);
            }
            Coroutine::sleep($breakTime);
        }

**Comment by 1107012776** [comment]
go(function () {
            $MqQueue = MqQueue::getInstance()->refreshConnect();
            $MqQueue->consumer()->setMoniterWaitError(function (\Exception $e){
                Logger::getInstance()->log('moniterWaitErro ' . var_export($e, true), Logger::LOG_LEVEL_INFO, 'DEBUG');//记录info级别日志//例子后面2个参数默认值
            })->setConfig('kd_sms_send_ex','hello')->listen(function(MqJob $obj) {
                Logger::getInstance()->log('log level info' . var_export($obj->getJobData(), true), Logger::LOG_LEVEL_INFO, 'DEBUG');//记录info级别日志//例子后面2个参数默认值
                var_dump($obj->getJobData(),'MqQueueProcess');
            });
        });

**Comment by hkj1994** [comment]
ok,辛苦了，connection 最好也可以 给到应用关闭， 不然发送产生的连接得等自动断开
