### ISSUE TITLE
链接一直抛异常

### ISSUE THREAD

**Issue by codewgh** [1107012776/easy-swoole-rabbitmq#6]
[Uncaught PhpAmqpLib\Exception\AMQPTimeoutException: The connection timed out after 5 sec while awaiting incoming data in /item/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:134

**Comment by 1107012776** [comment]
更新最新版本的

**Comment by 1107012776** [comment]
> [Uncaught PhpAmqpLib\Exception\AMQPTimeoutException: The connection timed out after 5 sec while awaiting incoming data in /item/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:134

使用最新版本的

**Comment by codewgh** [comment]
好的，已更新，没啥问题了

**Comment by 1107012776** [comment]
可以就行
